### ISSUE TITLE
graphql-tag/loader fails in Webpack 2

### ISSUE THREAD

**Issue by leebenson** [apollostack/graphql-tag#14]
In Webpack 2, this config:

```js
module: {
  loaders: [
    // GraphQL .gql parser
    {
      test: /\.gql$/,
      exclude: /node_modules/,
      loader: 'graphql-tag/loader',
    },
  ],
},
```

... yields:

> /Users/leebenson/dev/repo/front/node_modules/webpack-config/dist/Config.js:101
        throw _iteratorError;
        ^
TypeError: Cannot read property 'plugins' of undefined
    at Config.rootClientJs (/Users/leebenson/dev/repo/front/webpack/dev.js:12:5)
    at /Users/leebenson/dev/repo/front/node_modules/webpack-config/src/ConfigExtendCommand.js:80:50
    at Array.forEach (native)
    at /Users/leebenson/dev/repo/front/node_modules/webpack-config/src/ConfigExtendCommand.js:79:28
    at /Users/leebenson/dev/repo/front/node_modules/webpack-config/src/ConfigExtendCommand.js:74:50
    at Array.forEach (native)
    at ConfigExtendCommand.execute (/Users/leebenson/dev/repo/front/node_modules/webpack-config/src/ConfigExtendCommand.js:70:27)
    at executeCommand (/Users/leebenson/dev/repo/front/node_modules/webpack-config/src/Config.js:48:17)
    at Config.extend (/Users/leebenson/dev/repo/front/node_modules/webpack-config/src/Config.js:225:16)
    at Object.<anonymous> (/Users/leebenson/dev/repo/front/webpack/dev.js:10:29)
    at Module._compile (module.js:570:32)
    at loader (/Users/leebenson/dev/repo/front/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) as .js (/Users/leebenson/dev/repo/front/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by leebenson** [comment]
Actually, this may have something to do with my local config. I'll close until I can definitively point to `graphql-tag`.
